spring:
  profiles:
    include: dev
  jackson:
    serialization:
      write-dates-as-timestamps: true
  thymeleaf:
    prefix: classpath:/templates
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
