spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:cms
    username: root
    password: root
    initialization-mode: embedded
    schema: classpath:db/schema-h2.sql
    sql-script-encoding: UTF-8
  h2:
    console:
      enabled: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
