server:
  port: 80
spring:
  datasource:
    initialization-mode: never
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.99.100:3306/cms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
